#!/usr/bin/env python3
"""Write licensing/embedded.py from SUPABASE_URL / SUPABASE_ANON_KEY env vars.

Used by GitHub Actions before PyInstaller so release builds ship credentials.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "licensing" / "embedded.py"


def main() -> int:
    url = (os.environ.get("SUPABASE_URL") or "").strip().rstrip("/")
    key = (os.environ.get("SUPABASE_ANON_KEY") or "").strip()
    if not url or not key:
        print(
            "WARNING: SUPABASE_URL / SUPABASE_ANON_KEY not set — "
            "embedded credentials left empty (login gate will fail in packaged builds).",
            file=sys.stderr,
        )
        # Still write empty file so the module import path is stable.
    OUT.write_text(
        '"""Auto-generated by scripts/embed_supabase.py — do not edit by hand in CI."""\n\n'
        f"SUPABASE_URL = {url!r}\n"
        f"SUPABASE_ANON_KEY = {key!r}\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} (url={'set' if url else 'empty'}, key={'set' if key else 'empty'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
