#!/usr/bin/env python3
"""One-shot: deepen built-in styles with v3 fields + add 14 new styles."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STYLES = ROOT / "styles"

V3_PATCHES = {
    "history_documentary": {
        "version": 3,
        "visual_roles": {
            "weights": {
                "archival_evidence": 0.95,
                "document": 0.9,
                "event": 0.85,
                "map": 0.8,
                "timeline": 0.75,
                "character": 0.7,
                "location": 0.65,
                "atmosphere": 0.35,
            },
            "avoid": ["abstract", "generic stock"],
        },
        "source_preferences": {
            "ranked": ["archive", "youtube", "openverse", "pexels", "pixabay"],
            "avoid": [],
        },
        "search_guidance": {
            "prefer_terms": [
                "archival footage",
                "historical photograph",
                "period document",
                "newspaper",
                "map",
                "timeline",
            ],
            "avoid_terms": ["modern office", "generic businessman", "smartphone", "neon"],
            "evidence_bias": "high",
            "query_expansion": True,
        },
        "selection_rules": {
            "prefer_evidence_when_factual": True,
            "avoid_generic_when_specific": True,
            "repetition_penalty": 0.4,
            "provider_repetition_penalty": 0.2,
            "concept_repetition_penalty": 0.45,
        },
        "storytelling": {
            "narrative": "Evidence-led chronology with archival authenticity",
            "hook_strategy": "Open with a specific historical image or document",
            "evidence_priority": "high",
        },
        "shot_selection": {
            "establishing_weight": 0.55,
            "evidence_weight": 0.9,
            "atmosphere_weight": 0.25,
            "process_weight": 0.3,
        },
    },
    "premium_documentary": {
        "version": 3,
        "visual_roles": {
            "weights": {
                "establishing": 0.9,
                "location": 0.85,
                "person": 0.8,
                "atmosphere": 0.75,
                "event": 0.6,
                "comparison": 0.55,
                "reaction": 0.5,
            },
            "avoid": ["data", "document"],
        },
        "source_preferences": {
            "ranked": ["pexels", "pixabay", "youtube", "flow", "openverse"],
            "avoid": [],
        },
        "search_guidance": {
            "prefer_terms": [
                "cinematic",
                "establishing shot",
                "atmospheric",
                "environmental",
                "human subject",
            ],
            "avoid_terms": ["rapid montage", "generic stock", "low quality"],
            "evidence_bias": "medium",
            "query_expansion": True,
        },
        "selection_rules": {
            "prefer_evidence_when_factual": False,
            "avoid_generic_when_specific": True,
            "repetition_penalty": 0.45,
            "provider_repetition_penalty": 0.25,
            "concept_repetition_penalty": 0.5,
        },
        "storytelling": {
            "narrative": "Cinematic human/environment storytelling with visual continuity",
            "hook_strategy": "Strong establishing shot with restrained drama",
            "evidence_priority": "medium",
        },
        "shot_selection": {
            "establishing_weight": 0.9,
            "evidence_weight": 0.4,
            "atmosphere_weight": 0.85,
            "process_weight": 0.25,
        },
    },
    "ai_narration": {
        "version": 3,
        "visual_roles": {
            "weights": {
                "process": 0.9,
                "comparison": 0.85,
                "object": 0.8,
                "mechanism": 0.75,
                "data": 0.7,
                "abstract": 0.65,
                "establishing": 0.5,
            },
            "avoid": ["archival_evidence"],
        },
        "source_preferences": {
            "ranked": ["pexels", "pixabay", "flow", "youtube", "openverse"],
            "avoid": [],
        },
        "search_guidance": {
            "prefer_terms": [
                "diagram",
                "demonstration",
                "comparison",
                "process",
                "explainer",
                "object close-up",
            ],
            "avoid_terms": ["archival", "historical document", "slow broll only"],
            "evidence_bias": "low",
            "query_expansion": True,
        },
        "selection_rules": {
            "prefer_evidence_when_factual": False,
            "avoid_generic_when_specific": True,
            "repetition_penalty": 0.3,
            "provider_repetition_penalty": 0.2,
            "concept_repetition_penalty": 0.35,
        },
        "storytelling": {
            "narrative": "Fast coherent explanatory visuals with strong early hook",
            "hook_strategy": "Visual surprise in first 8 seconds",
            "evidence_priority": "low",
        },
        "shot_selection": {
            "establishing_weight": 0.35,
            "evidence_weight": 0.3,
            "atmosphere_weight": 0.25,
            "process_weight": 0.9,
        },
    },
    "space_documentary": {
        "version": 3,
        "visual_roles": {
            "weights": {
                "scientific_visualization": 0.95,
                "scale": 0.9,
                "event": 0.8,
                "object": 0.75,
                "location": 0.7,
                "comparison": 0.85,
                "atmosphere": 0.65,
            },
            "avoid": ["document", "person"],
        },
        "source_preferences": {
            "ranked": ["nasa", "youtube", "pexels", "flow", "pixabay", "openverse"],
            "avoid": [],
        },
        "search_guidance": {
            "prefer_terms": [
                "NASA mission",
                "spacecraft",
                "planet",
                "telescope",
                "scale comparison",
                "orbital",
            ],
            "avoid_terms": ["cartoon", "alien", "cityscape", "kitchen"],
            "evidence_bias": "high",
            "query_expansion": True,
        },
        "selection_rules": {
            "prefer_evidence_when_factual": True,
            "avoid_generic_when_specific": True,
            "repetition_penalty": 0.4,
            "provider_repetition_penalty": 0.2,
            "concept_repetition_penalty": 0.45,
        },
        "storytelling": {
            "narrative": "Scale, awe, and mission-accurate space imagery",
            "hook_strategy": "Open with cosmic scale or mission footage",
            "evidence_priority": "high",
        },
        "shot_selection": {
            "establishing_weight": 0.85,
            "evidence_weight": 0.75,
            "atmosphere_weight": 0.7,
            "process_weight": 0.55,
        },
    },
}

NEW_STYLES = [
    {
        "file": "ocean.json",
        "id": "ocean_marine_documentary",
        "name": "Ocean / Marine Documentary",
        "identity": {
            "description": "Deep-sea discovery, marine ecosystems, and ocean science with scale and atmosphere.",
            "tone": "immersive, scientific, vast",
            "best_for": ["ocean", "marine biology", "deep sea", "climate", "coral"],
        },
        "variety_family": "marine",
        "weights": {
            "scientific_density": 0.35,
            "cinematic_potential": 0.25,
            "visualization_need": 0.2,
            "emotional_intensity": 0.12,
            "educational_density": 0.08,
        },
        "visual_roles": {
            "location": 0.85,
            "scientific_visualization": 0.8,
            "process": 0.7,
            "scale": 0.75,
            "atmosphere": 0.7,
            "object": 0.6,
        },
        "sources": ["nasa", "openverse", "pexels", "youtube", "flow"],
        "prefer": ["hydrothermal vent", "ROV", "deep sea", "coral reef", "whale", "submarine"],
        "avoid": ["swimming pool", "bathtub", "beach resort"],
        "evidence_bias": "high",
        "ai_style": "scientific marine documentary — ROV footage, deep ocean, coral, whales, submersibles",
    },
    {
        "file": "science.json",
        "id": "science_documentary",
        "name": "Science Documentary",
        "identity": {
            "description": "Laboratory, experiment, and mechanism-driven science storytelling.",
            "tone": "curious, precise, explanatory",
            "best_for": ["physics", "biology", "chemistry", "research", "experiments"],
        },
        "variety_family": "science",
        "weights": {
            "scientific_density": 0.45,
            "visualization_need": 0.25,
            "educational_density": 0.15,
            "abstract_concept_density": 0.1,
            "cinematic_potential": 0.05,
        },
        "visual_roles": {
            "process": 0.9,
            "scientific_visualization": 0.85,
            "mechanism": 0.8,
            "data": 0.75,
            "object": 0.7,
            "comparison": 0.65,
        },
        "sources": ["nasa", "openverse", "pexels", "flow", "youtube"],
        "prefer": ["laboratory", "experiment", "microscope", "diagram", "scientific visualization"],
        "avoid": ["generic office", "unrelated nature broll"],
        "evidence_bias": "high",
        "ai_style": "scientific documentary visualization — experiments, lab equipment, diagrams, data",
    },
    {
        "file": "nature.json",
        "id": "nature_wildlife_documentary",
        "name": "Nature / Wildlife Documentary",
        "identity": {
            "description": "Wildlife behavior, habitats, and environmental context with cinematic patience.",
            "tone": "observational, immersive, respectful",
            "best_for": ["wildlife", "nature", "ecosystems", "conservation", "forests"],
        },
        "variety_family": "wildlife",
        "weights": {
            "cinematic_potential": 0.35,
            "emotional_intensity": 0.2,
            "scientific_density": 0.15,
            "visualization_need": 0.15,
            "educational_density": 0.15,
        },
        "visual_roles": {
            "establishing": 0.85,
            "location": 0.8,
            "process": 0.6,
            "scale": 0.55,
            "atmosphere": 0.75,
            "object": 0.5,
        },
        "sources": ["pexels", "pixabay", "youtube", "openverse", "flow"],
        "prefer": ["wildlife", "habitat", "predator prey", "forest", "migration", "aerial nature"],
        "avoid": ["zoo cage", "pet", "urban street"],
        "evidence_bias": "medium",
        "ai_style": "BBC-style wildlife documentary — animals in natural habitat, wide establishing habitats",
    },
    {
        "file": "true_crime.json",
        "id": "true_crime_documentary",
        "name": "True Crime / Investigation",
        "identity": {
            "description": "Evidence, investigation, and tension without sensational stock filler.",
            "tone": "tense, investigative, restrained",
            "best_for": ["crime", "investigation", "forensics", "cold case", "detective"],
        },
        "variety_family": "investigation",
        "weights": {
            "evidence_density": 0.35,
            "cinematic_potential": 0.25,
            "emotional_intensity": 0.2,
            "historical_density": 0.12,
            "hook_intensity": 0.08,
        },
        "visual_roles": {
            "document": 0.85,
            "event": 0.8,
            "location": 0.75,
            "archival_evidence": 0.9,
            "person": 0.65,
            "atmosphere": 0.55,
        },
        "sources": ["archive", "youtube", "pexels", "openverse"],
        "prefer": ["crime scene", "evidence", "police archive", "court document", "investigation"],
        "avoid": ["cartoon detective", "comedy", "generic handshake"],
        "evidence_bias": "high",
        "ai_style": "investigative documentary — evidence boards, archival news, locations, documents",
    },
    {
        "file": "technology.json",
        "id": "technology_documentary",
        "name": "Technology Documentary",
        "identity": {
            "description": "Devices, infrastructure, and innovation explained through process visuals.",
            "tone": "modern, clear, forward-looking",
            "best_for": ["technology", "computers", "engineering", "innovation", "silicon"],
        },
        "variety_family": "technology",
        "weights": {
            "scientific_density": 0.3,
            "explainer_density": 0.25,
            "visualization_need": 0.2,
            "cinematic_potential": 0.15,
            "educational_density": 0.1,
        },
        "visual_roles": {
            "process": 0.85,
            "object": 0.8,
            "mechanism": 0.75,
            "comparison": 0.7,
            "data": 0.65,
            "establishing": 0.5,
        },
        "sources": ["pexels", "pixabay", "youtube", "flow", "openverse"],
        "prefer": ["circuit board", "server room", "factory", "robotics", "semiconductor"],
        "avoid": ["1990s computer unless period", "generic typing"],
        "evidence_bias": "medium",
        "ai_style": "technology documentary — chips, data centers, robotics, clean modern labs",
    },
    {
        "file": "future_tech.json",
        "id": "future_tech_documentary",
        "name": "Future / Emerging Tech",
        "identity": {
            "description": "Speculative but grounded visuals for AI, biotech, and emerging systems.",
            "tone": "speculative, sleek, explanatory",
            "best_for": ["AI", "future", "biotech", "quantum", "emerging tech"],
        },
        "variety_family": "future",
        "weights": {
            "explainer_density": 0.3,
            "abstract_concept_density": 0.25,
            "scientific_density": 0.2,
            "visualization_need": 0.15,
            "hook_intensity": 0.1,
        },
        "visual_roles": {
            "abstract": 0.75,
            "process": 0.8,
            "scientific_visualization": 0.85,
            "comparison": 0.7,
            "object": 0.65,
        },
        "sources": ["flow", "pexels", "pixabay", "youtube", "nasa"],
        "prefer": ["AI visualization", "neural network", "quantum", "futuristic lab", "hologram"],
        "avoid": ["cartoon robot", "cyberpunk cliché"],
        "evidence_bias": "low",
        "ai_style": "grounded futurist documentary — clean sci-tech visualization, not cartoon cyberpunk",
    },
    {
        "file": "geopolitics.json",
        "id": "geopolitics_documentary",
        "name": "Geopolitics / World Affairs",
        "identity": {
            "description": "Maps, borders, leaders, and event footage for global affairs.",
            "tone": "analytical, authoritative, current",
            "best_for": ["geopolitics", "diplomacy", "conflict", "international relations"],
        },
        "variety_family": "geopolitics",
        "weights": {
            "historical_density": 0.25,
            "evidence_density": 0.25,
            "chronology_density": 0.2,
            "cinematic_potential": 0.15,
            "educational_density": 0.15,
        },
        "visual_roles": {
            "map": 0.9,
            "event": 0.85,
            "location": 0.8,
            "document": 0.75,
            "person": 0.7,
            "timeline": 0.65,
        },
        "sources": ["archive", "youtube", "openverse", "pexels"],
        "prefer": ["map", "border", "summit", "protest", "military parade", "flag"],
        "avoid": ["tourist postcard", "unrelated nature"],
        "evidence_bias": "high",
        "ai_style": "geopolitical documentary — maps, news archive, diplomatic settings, conflict zones",
    },
    {
        "file": "business.json",
        "id": "business_economics_documentary",
        "name": "Business / Economics",
        "identity": {
            "description": "Markets, infrastructure, and human impact — not generic handshake stock.",
            "tone": "analytical, grounded, contemporary",
            "best_for": ["economics", "finance", "markets", "trade", "industry"],
        },
        "variety_family": "business",
        "weights": {
            "educational_density": 0.3,
            "abstract_concept_density": 0.2,
            "cinematic_potential": 0.2,
            "evidence_density": 0.15,
            "chronology_density": 0.15,
        },
        "visual_roles": {
            "data": 0.8,
            "location": 0.75,
            "process": 0.7,
            "comparison": 0.65,
            "establishing": 0.6,
            "document": 0.55,
        },
        "sources": ["pexels", "pixabay", "youtube", "archive", "openverse"],
        "prefer": ["stock exchange", "factory", "supply chain", "chart", "port", "agriculture"],
        "avoid": ["handshake", "generic businessman", "empty office"],
        "evidence_bias": "medium",
        "ai_style": "business documentary — real infrastructure, charts, ports, factories, not cliché office",
    },
    {
        "file": "biography.json",
        "id": "biography_documentary",
        "name": "Biography / Human Story",
        "identity": {
            "description": "Portrait-led human stories with period context and emotional restraint.",
            "tone": "intimate, empathetic, narrative",
            "best_for": ["biography", "profiles", "memoir", "human interest"],
        },
        "variety_family": "biography",
        "weights": {
            "emotional_intensity": 0.3,
            "historical_density": 0.25,
            "cinematic_potential": 0.25,
            "evidence_density": 0.12,
            "archival_visual_need": 0.08,
        },
        "visual_roles": {
            "person": 0.9,
            "character": 0.85,
            "archival_evidence": 0.75,
            "location": 0.7,
            "reaction": 0.65,
            "atmosphere": 0.6,
        },
        "sources": ["archive", "youtube", "openverse", "pexels"],
        "prefer": ["portrait", "archival photograph", "home town", "period footage"],
        "avoid": ["random crowd", "unrelated landscape"],
        "evidence_bias": "high",
        "ai_style": "biographical documentary — portraits, period locations, personal artifacts",
    },
    {
        "file": "military.json",
        "id": "military_war_documentary",
        "name": "Military / War History",
        "identity": {
            "description": "Archival combat footage, maps, and equipment with historical accuracy.",
            "tone": "grave, factual, chronological",
            "best_for": ["war", "military history", "conflict", "battle", "veterans"],
        },
        "variety_family": "military",
        "weights": {
            "historical_density": 0.35,
            "evidence_density": 0.3,
            "archival_visual_need": 0.2,
            "chronology_density": 0.1,
            "emotional_intensity": 0.05,
        },
        "visual_roles": {
            "archival_evidence": 0.95,
            "event": 0.9,
            "map": 0.85,
            "object": 0.7,
            "location": 0.75,
            "timeline": 0.8,
        },
        "sources": ["archive", "youtube", "openverse", "nasa"],
        "prefer": ["archival war footage", "battle map", "tank", "soldiers historical", "military document"],
        "avoid": ["modern action movie", "video game", "toy soldier"],
        "evidence_bias": "high",
        "ai_style": "military history documentary — authentic archival combat, maps, period equipment",
    },
    {
        "file": "ancient_history.json",
        "id": "ancient_history_documentary",
        "name": "Ancient History / Archaeology",
        "identity": {
            "description": "Ruins, artifacts, maps, and excavation evidence for ancient civilizations.",
            "tone": "scholarly, wonder, grounded",
            "best_for": ["ancient history", "archaeology", "civilizations", "ruins", "artifacts"],
        },
        "variety_family": "ancient",
        "weights": {
            "historical_density": 0.4,
            "evidence_density": 0.25,
            "archival_visual_need": 0.2,
            "visualization_need": 0.1,
            "cinematic_potential": 0.05,
        },
        "visual_roles": {
            "archival_evidence": 0.9,
            "location": 0.85,
            "object": 0.8,
            "map": 0.75,
            "document": 0.7,
            "scale": 0.6,
        },
        "sources": ["openverse", "archive", "youtube", "pexels"],
        "prefer": ["ruins", "excavation", "artifact", "ancient map", "temple", "inscription"],
        "avoid": ["fantasy castle", "modern city"],
        "evidence_bias": "high",
        "ai_style": "archaeological documentary — ruins, artifacts, excavation sites, ancient maps",
    },
    {
        "file": "mystery.json",
        "id": "mystery_documentary",
        "name": "Mystery / Unexplained",
        "identity": {
            "description": "Atmosphere and evidence balanced — intrigue without cheap horror stock.",
            "tone": "intriguing, atmospheric, skeptical",
            "best_for": ["mystery", "unexplained", "paranormal skeptic", "cold cases"],
        },
        "variety_family": "mystery",
        "weights": {
            "emotional_intensity": 0.25,
            "hook_intensity": 0.25,
            "cinematic_potential": 0.2,
            "evidence_density": 0.15,
            "abstract_concept_density": 0.15,
        },
        "visual_roles": {
            "atmosphere": 0.8,
            "location": 0.75,
            "document": 0.7,
            "event": 0.65,
            "abstract": 0.6,
            "establishing": 0.7,
        },
        "sources": ["pexels", "youtube", "archive", "openverse"],
        "prefer": ["fog", "night", "abandoned", "archive newspaper", "investigation board"],
        "avoid": ["cartoon ghost", "halloween clip art"],
        "evidence_bias": "medium",
        "ai_style": "mystery documentary — moody locations, documents, restrained atmosphere",
    },
    {
        "file": "educational.json",
        "id": "educational_explainer",
        "name": "Educational Explainer",
        "identity": {
            "description": "Clear teaching visuals — diagrams, demos, and step-by-step process.",
            "tone": "friendly, clear, pedagogical",
            "best_for": ["education", "tutorial", "classroom", "how-it-works"],
        },
        "variety_family": "explainer",
        "weights": {
            "educational_density": 0.4,
            "explainer_density": 0.3,
            "visualization_need": 0.2,
            "abstract_concept_density": 0.1,
        },
        "visual_roles": {
            "process": 0.95,
            "comparison": 0.85,
            "object": 0.8,
            "data": 0.75,
            "mechanism": 0.8,
            "abstract": 0.6,
        },
        "sources": ["pexels", "pixabay", "youtube", "flow", "openverse"],
        "prefer": ["diagram", "whiteboard", "demonstration", "step by step", "classroom"],
        "avoid": ["dramatic cinematic only", "unrelated broll"],
        "evidence_bias": "medium",
        "ai_style": "educational explainer — diagrams, demonstrations, clear labeled visuals",
    },
    {
        "file": "news.json",
        "id": "news_current_affairs",
        "name": "News / Current Affairs",
        "identity": {
            "description": "Event footage, locations, and documents for timely reporting style.",
            "tone": "urgent, factual, contemporary",
            "best_for": ["news", "current events", "breaking", "reporting", "journalism"],
        },
        "variety_family": "news",
        "weights": {
            "evidence_density": 0.3,
            "chronology_density": 0.2,
            "cinematic_potential": 0.15,
            "historical_density": 0.15,
            "hook_intensity": 0.2,
        },
        "visual_roles": {
            "event": 0.9,
            "location": 0.85,
            "person": 0.75,
            "document": 0.7,
            "reaction": 0.65,
            "establishing": 0.6,
        },
        "sources": ["youtube", "archive", "pexels", "openverse"],
        "prefer": ["news footage", "press conference", "protest", "headline", "location b-roll"],
        "avoid": ["staged stock smile", "unrelated nature"],
        "evidence_bias": "high",
        "ai_style": "news documentary — event footage, locations, press scenes, documents",
    },
]


def _base_style(spec: dict) -> dict:
    roles = spec["visual_roles"]
    return {
        "id": spec["id"],
        "version": 3,
        "name": spec["name"],
        "identity": spec["identity"],
        "visual": {
            "treatment": spec["variety_family"],
            "camera": {"preferred": ["hold", "subtle_drift", "push_in"], "intensity": 0.4},
            "motion_rules": {},
            "variety": {"min_unique_keys": 0.6, "avoid_repetition": True},
        },
        "pacing": {
            "default": "normal",
            "hook": "normal",
            "exposition": "normal",
            "evidence": "normal",
            "climax": "normal",
            "reflection": "slow",
            "transition_density": 0.3,
        },
        "transitions": {"default": "cut", "preferred": ["cut", "dissolve"], "avoid": ["flash"]},
        "audio": {
            "ambience_intensity": 0.55,
            "sfx_intensity": 0.4,
            "music_intensity": 0.5,
            "music_duck_db": -10,
        },
        "hook": {"window_seconds": 30, "attention_target": 0.7, "prefer_visual_change": True},
        "assets": {"preferred": ["stock_video", "youtube_video", "stock_image"], "avoid_repetition": True},
        "captions": {"style": "documentary", "density": "medium", "emphasis": "subtle"},
        "ai_visual_prompt": {
            "style": spec["ai_style"],
            "realism": 0.8,
            "composition": "subject-forward documentary framing",
            "avoid": spec["avoid"][:4],
        },
        "intelligence": {
            "weights": spec["weights"],
            "preview_visual": spec["name"].split("/")[0].strip(),
            "preview_camera": "Documentary",
            "preview_pacing": "Purpose-driven",
            "preview_audio": "Balanced",
            "variety_family": spec["variety_family"],
            "influences": [spec["variety_family"]],
        },
        "visual_roles": {"weights": roles, "avoid": ["generic stock"]},
        "source_preferences": {"ranked": spec["sources"], "avoid": []},
        "search_guidance": {
            "prefer_terms": spec["prefer"],
            "avoid_terms": spec["avoid"],
            "evidence_bias": spec["evidence_bias"],
            "query_expansion": True,
        },
        "selection_rules": {
            "prefer_evidence_when_factual": spec["evidence_bias"] == "high",
            "avoid_generic_when_specific": True,
            "repetition_penalty": 0.35,
            "provider_repetition_penalty": 0.25,
            "concept_repetition_penalty": 0.4,
        },
        "storytelling": {
            "narrative": spec["identity"]["description"],
            "hook_strategy": "Lead with the most specific visual evidence available",
            "evidence_priority": spec["evidence_bias"],
        },
        "shot_selection": {
            "establishing_weight": 0.5,
            "evidence_weight": 0.7 if spec["evidence_bias"] == "high" else 0.4,
            "atmosphere_weight": 0.45,
            "process_weight": 0.5,
        },
    }


def patch_existing() -> None:
    mapping = {
        "history_documentary": "history.json",
        "premium_documentary": "documentary.json",
        "ai_narration": "ai_narration.json",
        "space_documentary": "space.json",
    }
    for sid, fname in mapping.items():
        path = STYLES / fname
        data = json.loads(path.read_text(encoding="utf-8"))
        patch = V3_PATCHES[sid]
        for k, v in patch.items():
            data[k] = v
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"patched {fname}")


def create_new() -> None:
    for spec in NEW_STYLES:
        path = STYLES / spec["file"]
        data = _base_style(spec)
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"created {spec['file']}")


if __name__ == "__main__":
    patch_existing()
    create_new()
